### ISSUE TITLE
Enhancement - Let extensions return `Transition` instead of Unit

### ISSUE THREAD

**Issue by turastory** [arunkumar9t2/transition-x#6]
```kotlin
container.prepareTransition {}
container.prepareAutoTransition {}
```

These two extensions both return Unit - which is not that helpful when you want for example, to add some listeners to Transition.

So I'm using TransitionSetBuilder directly now:

```kotlin
typealias TransitionBuilder =
    TransitionSetBuilder<TransitionSet>.() -> Unit

private fun prepare(
    builder: TransitionBuilder = {}
): Transition {
    return TransitionSetBuilder<TransitionSet>(AutoTransition())
        .apply(builder).transition
        .apply { TransitionManager.beginDelayedTransition(sceneRoot, this) }
}
```

It would be great if library supports this.

**Comment by arunkumar9t2** [comment]
Hi, thanks for reporting this. I see there are two concerns in this issue.

1. Accessing `Transition` instances. `prepareXTransition` as the name suggests calles `beginDelayedTransition` after constructing the `Transition` instance from the DSL. There is a [separate method call](https://arunkumar9t2.github.io/transition-x/transitionx/in.arunkumarsampath.transitionx/transition-set.html) to construct `transitionSet`s with the DSL which returns the created instance. 

Example:

```kotlin
val moveTransition = transitionSet {
    moveResize()
    scaleRotate()
}
```
Sample [usage](https://github.com/arunkumar9t2/transition-x/blob/fddc4ba65ac5806676e0b08474fc2d714c05b3fd/sample/src/main/java/in/arunkumarsampath/transitionx/sample/home/transitionsamples/AnimatedBottomNavigationFragment.kt#L68
)
 
2. Adding listeners: the library already provides listeners as part of the DSL. For example, [onEnd](https://arunkumar9t2.github.io/transition-x/transitionx/in.arunkumarsampath.transitionx.transition/-transition-builder/on-end.html) block gets executed once the transition finishes. Are you finding this not sufficient for your use case?

Example:

```kotlin
rootCoordinatorLayout.prepareTransition {
    onStart { 
        // Started!
    }
    moveResize {
        +image1
    }
    onEnd { 
        // I am done :)
    }
}
```

**Comment by arunkumar9t2** [comment]
Closing the issue for now. Please don't hesitate to open if you have any questions.
